# Ollama Server Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/instance: test-llamastack-26012903-ollama
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-llamastack-26012903-ollama
    app.kubernetes.io/part-of: test-llamastack-26012903
    app.kubernetes.io/component: ollama
  name: test-llamastack-26012903-ollama
spec:
  ports:
    - name: http
      port: 11434
      protocol: TCP
      targetPort: 11434
  selector:
    app.kubernetes.io/instance: test-llamastack-26012903-ollama
  type: ClusterIP
