# Service for Kubernetes MCP Server
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/instance: test-llamastack-26012903-mcp-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-llamastack-26012903-mcp-server
  name: test-llamastack-26012903-mcp-server
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/instance: test-llamastack-26012903-mcp-server

