apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: test-llamastack-26012903-gitops-repository
spec:
  url: https://github.com/fpetk-rolling-demo/test-llamastack-26012903-gitops
